<?php
namespace tlc\tts;

use mysqli;

if(!defined('APP_DIR')) { http_response_code(405); error_log("Invalid entry attempt: ".__FILE__); die(); }

require_once app_file('include/logger.php');

/**
 * The MySQLConnnection function creates a single connetion the mysql server.
 *   The authentication uses the following parameters initialized from the
 *   package config (.ini) file
 *
 *   tlc-ttsurvey.ini file:
 *      HOST     - mysql_host
 *      USERNAME - mysql_username
 *      PASSWORD - mysql_password
 *      SCHEMA   - mysql_host
 *
 *   Additionally, t sets the charset based on mysql.charset if specified
 *   or 'utf8' if not specified.
 *
 * Note that as logger requires settings from the database to function, 
 *   we cannot use any of its logging functions from with MySQLConnection,
 *   we must used the native error_log function instead (which will write
 *   to the generic PHP error log and not the app specific log).
 *   Similarly, we cannot use internal_error as that uses log_error.
 * 
 * @return mysqli 
 */
function MySQLConnection() 
{
  static $conn;
  if(!$conn) {
    try {
      $config = parse_ini_file(APP_DIR.'/'.PKG_NAME.'.ini',true);
      $username = $config['mysql_username'];
      $password = $config['mysql_password'];
      $schema   = $config['mysql_schema'];
      $host     = $config['mysql_host'];
      $charset  = $config['mysql_charset'] ?? 'utf8mb4';

      mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
      $conn = new \mysqli($host, $username, $password, $schema);
    } 
    catch(\mysqli_sql_exception $e) {
      error_log(sprintf("mysqli(%s, %s, %s, %s)",$host,$username,$password,$schema),0);
      die();
    }
    if( ! $conn->set_charset($charset) ) 
    { 
      // internal_error is ok now as we have a database connection
      internal_error('Failed to set charset to '.$charset);
    }
  }
  return $conn;
}

/**
 * Initiates a MySQL transaction
 * Changes in a transaction won't be committed until MySQLCommit is called
 * @return void 
 */
function MySQLBeginTransaction() 
{ MySQLConnection()->begin_transaction(); }

/**
 * Rolls back a MySQL transaction.
 * This undoes all modifications in the current transaction
 * @return void 
 */
function MySQLRollback()
{ MySQLConnection()->rollback(); }

/**
 * Commits the changes in a MySQL transaction
 * @return void 
 */
function MySQLCommit()
{ MySQLConnection()->commit(); }

/**
 * Prepares and executes a mysqli query
 * Returns
 *   - false: failure to execute
 *   - 0: query ran, but nothing changed
 *   - N: number of rows modified by the query
 * @param string $query 
 * @param null|string $types 
 * @param mixed ...$params 
 * @return mixed 
 */
function MySQLExecute(string $query,?string $types=null,mixed ...$params) : mixed
{
  if(preg_match("/^\s*select/i",$query)) {
    internal_error("Use MySQLSelect for select queries");
  }

  $conn = MySQLConnection();

  try {
    if($types) {
      $stmt = $conn->prepare($query);
      $stmt->bind_param($types, ...$params);
      if( $stmt->execute() ) {
        return $stmt->affected_rows;
      }
    } else {
      if($conn->query($query)) {
        return $conn->affected_rows;
      }
    }
  }
  catch(\mysqli_sql_exception $e) {
    log_error($e->getMessage());
  }

  log_warning("Failed:: MySQLExecute($query,$types,".json_encode($params).")");
  return false;
}

/**
 * Autogenerated row ID from last insert command
 * Must be called immediately after the insert command is run
 * @return int|string 
 */
function MySQLInsertID()
{
  $conn = MySQLConnection();
  return $conn->insert_id;
}

/**
 * Prepares and executes a mysqli select query
 * Returns:
 * - false if the prepared statement could not be compiled
 * - null if the query returned no rows from the query
 * - selected rows:
 *   - If $all is true returns all rows that match query
 *     - array of associative arrays if $mode = MYSQLI_ASSOC
 *     - array of indexed arrays if $mode = MYSQLI_NUM
 *   - If $all is false returns first row that maches query
 *     - associative array if $mode = MYSQLI_ASSOC
 *     - indexed array if $mode = MYSQLI_NUM
 * 
 * @param bool $all  true:returns all rows, false:return a single row
 * @param int $mode  MYSQLI_ASSOC, MYSQLI_NUM, or MYSQLI_BOTH (see mysqli docs)
 * @param string $query MySQL select query
 * @param null|string $types prepared statement parameter types
 * @param array $params prepared statement parameter values
 * @return mixed 
 */
function MySQLSelect(bool $all,int $mode,string $query,?string $types=null,array $params=[]) : mixed
{
  if(! preg_match("/^\s*select/i",$query)) {
    internal_error("Use MySQLSelect for non-select queries");
  }

  $conn = MySQLConnection();

  if($types) {
    $stmt = $conn->prepare($query);
    $stmt->bind_param($types, ...$params);
    if( $stmt->execute() ) {
      $result = $stmt->get_result();
    }
  } else {
    $result = $conn->query($query);
  }

  if($result) {
    if($all) {
      return $result->fetch_all($mode);
    } else {
      return $result->fetch_array($mode);
    }
  }
  log_dev("Failed MySQLSelect($all,$mode,$query,$types,".json_encode($params).")");
  return false;
}

/**
 * Prepares and executes a mysqli select query
 * Returns all rows as associative arrays with keys equal to column names
 * Returns
 * - false if the prepared statement could not be compiled
 * - null if the query returned no rows from the query
 * @param string $query 
 * @param null|string $types 
 * @param mixed ...$params 
 * @return mixed 
 */
function MySQLSelectRows(string $query,?string $types=null,mixed ...$params) : mixed
{
  return MySQLSelect(true,MYSQLI_ASSOC,$query,$types,$params);
}

/**
 * Prepares and executes a mysqli select query
 * Returns single associative array with keys equal to column names
 * Returns:
 * - false if the prepared statement could not be compiled
 * - null if the query returned no rows from the query
 * @param string $query 
 * @param null|string $types 
 * @param mixed ...$params 
 * @return mixed 
 */
function MySQLSelectRow(string $query,?string $types=null,mixed ...$params) : mixed
{
  return MySQLSelect(false,MYSQLI_ASSOC,$query,$types,$params);
}

/**
 * Prepares and executes a mysqli select query
 * Returns all rows as indexed arrays
 * Returns
 * - false if the prepared statement could not be compiled
 * - null if the query returned no rows from the query
 * @param string $query 
 * @param null|string $types 
 * @param mixed ...$params 
 * @return mixed 
 */
function MySQLSelectArrays(string $query,?string $types=null,mixed ...$params) : mixed
{
  return MySQLSelect(true,MYSQLI_NUM,$query,$types,$params);
}

/**
 * Prepares and executes a mysqli select query
 * Returns single indexed array (first row to match the query)
 * Returns
 * - false if the prepared statement could not be compiled
 * - null if the query returned no rows from the query
 * @param string $query 
 * @param null|string $types 
 * @param mixed ...$params 
 * @return mixed 
 */
function MySQLSelectArray(string $query,?string $types=null,mixed ...$params) : mixed
{
  return MySQLSelect(false,MYSQLI_NUM,$query,$types,$params);
}

/**
 * Prepares and executes a mysqli select query to find a single value
 * Returns a single value (from first row to match the query)
 * Returns
 * - null if the query returned no rows from the query
 * @param string $query 
 * @param null|string $types 
 * @param mixed ...$params 
 * @return mixed 
 */
function MySQLSelectValue(string $query,?string $types=null,mixed ...$params) : mixed
{
  $row = MySQLSelectArray($query,$types,...$params);
  return $row[0] ?? null;
}

/**
 * Prepares and executes a mysqli select query to find a single value in each row
 * Returns an indexed array with the selected columnn value from each row
 * Returns
 * - null if the query returned no rows from the query
 * @param string $query 
 * @param null|string $types 
 * @param mixed ...$params 
 * @return mixed 
 */
function MySQLSelectValues(string $query,?string $types=null,mixed ...$params) : mixed
{
  $rows = MySQLSelectArrays($query,$types,...$params);
  $values = array();
  foreach($rows as $row) { $values[] = $row[0]; }
  return $values;
}

