<?php
namespace tlc\tts;

use mysqli;
use mysqli_stmt;
use mysqli_sql_exception;

if(!defined('APP_DIR')) { http_response_code(405); error_log("Invalid entry attempt: ".__FILE__); die(); }

require_once app_file('include/logger.php');

/**
 * Returns a singleton mysqli connection (constructing it if necessary) based 
 *   on the connection credentials in the config .ini file.
 *   tlc-ttsurvey.ini file:
 *      HOST     - mysql_host
 *      USERNAME - mysql_username
 *      PASSWORD - mysql_password
 *      SCHEMA   - mysql_host
 *      CHARSET  - mysql_charset (utf8mb4 if not specified)
 * 
 * @return mysqli 
 * @note On failure, kills the script with die().
 */
function MySQLConnection() 
{
  static $conn;
  if(!$conn) {
    try {
      $config = parse_ini_file(APP_DIR.'/'.PKG_NAME.'.ini',true);
      $username = $config['mysql_username'];
      $password = $config['mysql_password'];
      $schema   = $config['mysql_schema'];
      $host     = $config['mysql_host'];
      $charset  = $config['mysql_charset'] ?? 'utf8mb4';

      mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
      $conn = new \mysqli($host, $username, $password, $schema);
    } 
    catch(\mysqli_sql_exception $e) {
      // Note that as logger requires settings from the database to function, 
      //   we cannot use any of its logging functions here.
      error_log(sprintf("mysqli(%s, %s, %s, %s)",$host,$username,$password,$schema),0);
      die();
    }
    if( ! $conn->set_charset($charset) ) 
    { 
      // internal_error is ok now as we have a database connection
      internal_error('Failed to set charset to '.$charset);
    }
  }
  return $conn;
}

/**
 * Initiates a mysqli transaction
 * @return void 
 */
function MySQLBeginTransaction() { MySQLConnection()->begin_transaction(); }

/**
 * Rolls back a mysqli transaction
 * @return void 
 */
function MySQLRollback() { MySQLConnection()->rollback(); }

/**
 * Commits a mysqli transaction
 * @return void 
 */
function MySQLCommit() { MySQLConnection()->commit(); }

/**
 * Returns the auto-increment value from the last query
 * @return int
 * @note Must be called immediately after the INSERT query to get the 
 *   autogenerated row ID
 */
function MySQLInsertID() : int {
  $conn = MySQLConnection();
  return (int) $conn->insert_id;
}


class MySQLPreparedStatement
{
  protected string $query;
  protected string $types;
  protected int    $n_params;
  protected int    $log_depth;

  protected mysqli      $conn;
  protected mysqli_stmt $stmt;

  /**
   * MySQLPreparedStatement constructor
   * @param string $query Prepared statement query string (with ? pararameter placeholders)
   * @param string $types Prepared statement parameter types
   * @param bool $wrapped Instance is wrapped in a convenience function
   * @return void 
   */
  protected function __construct(string $query, string $types, bool $wrapped)
  {
    $this->log_depth = $wrapped ? 2 : 1;
    $this->n_params = substr_count($query,"?");
    if( strlen($types) !== $this->n_params) {
      internal_error("Mismatch between prepared statement and types length",$this->log_depth);
    }

    $this->query = $query;
    $this->types = $types;
    $this->conn  = MySQLConnection();
    $this->stmt = $this->conn->prepare($query);
  }

  /**
   * Binds and executes the prepared statement with the supplied parameters
   * @param array $params Prepared statement parameter values
   * @return void
   */
  protected function _bind_and_exec(...$params)
  {
    if( count($params) !== $this->n_params) {
      internal_error("Mismatch between prepared statement and parameter count",$this->log_depth);
    }
    try {
      if(count($params)) {
        $this->stmt->bind_param($this->types, ...$params);
      }
      $this->stmt->execute();
    } catch(mysqli_sql_exception $e) {
      internal_error($e->getMessage(),$this->log_depth);
    }
  }
}

class MySQLPreparedExec extends MySQLPreparedStatement
{
  /**
   * MySQLPreparedExec constructor
   * @param string $query Prepared statement query string (with ? pararameter placeholders)
   * @param string $types Prepared statement parameter types
   * @param bool $wrapped Instance is wrapped in a convenience function
   * @return void 
   * 
   * @note Wrapped should only ever be set to true when MySQLPreparedExec is 
   *       being wrapped in one of the provided convenience functions below.
   *       Its sole purpose is to provide more accurate error logging
   * 
   * @note This class cannot be used with SELECT queries.  Doing so
   *       triggers internal error handling
   */
  public function __construct(string $query, string $types='', bool $wrapped=false)
  {
    if (preg_match("/^\s*select/i", $query)) {
      internal_error(
        "MySQLPreparedExec does not work with SELECT queries," . 
        "Use MySQLPreparedSelect instead",
        $wrapped ? 2 : 1);
    }
    parent::__construct($query,$types,$wrapped);
  }

  /**
   * Executes the prepared statement
   * @param array $params Prepared statement parameter values
   * @return int Number of affected rows
   */
  public function run(...$params) : int
  {
    $this->_bind_and_exec(...$params);
    return $this->stmt->affected_rows;
  }
}

class MySQLPreparedSelect extends MySQLPreparedStatement
{
  /**
   * MySQLPreparedSelect constructor
   * @param string $query Prepared statement query string (with ? pararameter placeholders)
   * @param string $types Prepared statement parameter types
   * @param bool $wrapped Instance is wrapped in a convenience function
   * @return void 
   * 
   * @note Wrapped should only ever be set to true when MySQLPreparedExec is 
   *       being wrapped in one of the provided convenience functions below.
   *       Its sole purpose is to provide more accurate error logging
   * 
   * @note This class is only to be used with SELECT queries.  Any other type
   *       of query triggers internal error handling
   */
  public function __construct(string $query, string $types='',bool $wrapped=false)
  {
    if (! preg_match("/^\s*select/i", $query)) {
      internal_error(
        "MySQLPreparedExec only works with SELECT queries," . 
        "Use MySQLPreparedExec instead",
        $wrapped ? 2 : 1);
    }
    parent::__construct($query,$types,$wrapped);
  }

  /**
   * Executes the prepared statement and returns all results as an array of associative arrays
   * @param array $params Prepared statement parameter values
   * @return array All matching row data as array of associative arrays
   */
  public function fetchAllAssoc(...$params) : array 
  {
    $this->_bind_and_exec(...$params);
    $result = $this->stmt->get_result();
    $rval = $result->fetch_all(MYSQLI_ASSOC);
    $result->free();
    return $rval;
  }

  /**
   * Executes the prepared statement and returns the first result as an associative array
   * @param array $params Prepared statement parameter values
   * @return array First matching row as an associative array (or [])
   */
  public function fetchOneAssoc(...$params) : array 
  {
    $this->_bind_and_exec(...$params);
    $result = $this->stmt->get_result();
    $rval = $result->fetch_assoc() ?? [];
    $result->free();
    return $rval;
  }

  /**
   * Executes the prepared statement and returns all results as an array of indexed arrays
   * @param array $params Prepared statement parameter values
   * @return array All matching row data as an array of indexed arrays
   */
  public function fetchAllIndexed(...$params) : array 
  {
    $this->_bind_and_exec(...$params);
    $result = $this->stmt->get_result();
    $rval = $result->fetch_all(MYSQLI_NUM);
    $result->free();
    return $rval;
  }

  /**
   * Executes the prepared statement and returns the first result as an indexed array
   * @param array $params Prepared statement parameter values
   * @return array First matching row as an indexed array (or [])
   */
  public function fetchOneIndexed(...$params) : array 
  {
    $this->_bind_and_exec(...$params);
    $result = $this->stmt->get_result();
    $rval = $result->fetch_array(MYSQLI_NUM) ?? [];
    $result->free();
    return $rval;
  }

  /**
   * Executes the prepared statement and returns the first value from each row
   * @param array $params Prepared statement parameter values
   * @return array Column value from all matched rows (or [])
   *
   * @note This function only returns the first value from each row, even if the query
   *       selects more than a single column
   */
  public function fetchColumn(...$params) : array
  {
    $this->_bind_and_exec(...$params);
    $result = $this->stmt->get_result();
    $rval = [];
    while( ($value = $result->fetch_column(0)) !== false ) {
      $rval[] = $value;
    }
    $result->free();
    return $rval;
  }

  /**
   * Executes the prepared statement and returns the first value from the first row
   * @param array $params Prepared statement parameter values
   * @return null|int|float|string Value from query (or null)
   * 
   * @note this function only returns the first value from the row, even if the query
   *   selects more than a single column
  */
  public function fetchValue(...$params) : null|int|float|string
  {
    $this->_bind_and_exec(...$params);
    $result = $this->stmt->get_result();
    $rval = $result->fetch_column(0);
    $result->free();
    return $rval;
  }
}

/**
 * Execute a non-SELECT MySQL query and returns number of affected rows
 * @param string $query Prepared statement query string (with ? pararameter placeholders)
 * @param string $types Prepared statement parameter types (default='')
 * @param array $params Prepared statement parameter values
 * @return int Number of affected rows
 */
function MySQLExecute(string $query,string $types='', ...$params) : int
{
  $stmt = new MySQLPreparedExec($query,$types,wrapped:true);
  return $stmt->run(...$params);
}

/**
 * Executes a SELECT query and returns all results as an array of associative arrays
 * @param string $query Prepared statement query string (with ? pararameter placeholders)
 * @param string $types Prepared statement parameter types (default='')
 * @param array $params Prepared statement parameter values
 * @return array All matching row data as array of associative arrays
 */
function MySQLFetchAllAssoc(string $query,string $types='',...$params) : array
{
  $stmt = new MySQLPreparedSelect($query,$types,wrapped:true);
  return $stmt->fetchAllAssoc(...$params);
}

/**
 * Executes a SELECT query and returns the first result as an associative array
 * @param string $query Prepared statement query string (with ? pararameter placeholders)
 * @param null|string $types Prepared statement parameter types
 * @param array $params Prepared statement parameter values
 * @return array First matching row as an associative array (or [])
 */
function MySQLFetchOneAssoc(string $query,?string $types=null,...$params) : array
{
  $stmt = new MySQLPreparedSelect($query,$types,wrapped:true);
  return $stmt->fetchOneAssoc(...$params);
}

/**
 * Executes a SELECT query and returns all results as an array of indexed arrays
 * @param string $query Prepared statement query string (with ? pararameter placeholders)
 * @param string $types Prepared statement parameter types (default='')
 * @param array $params Prepared statement parameter values
 * @return array All matching row data as array of indexed arrays
 */
function MySQLFetchAllIndexed(string $query,string $types='',...$params) : array
{
  $stmt = new MySQLPreparedSelect($query,$types,wrapped:true);
  return $stmt->fetchAllIndexed(...$params);
}

/**
 * Executes a SELECT query and returns the first result as an indexed array
 * @param string $query Prepared statement query string (with ? pararameter placeholders)
 * @param string $types Prepared statement parameter types (default='')
 * @param array $params Prepared statement parameter values
 * @return array First matching row as an indexed array (or [])
 */
function MySQLFetchOneIndexed(string $query,string $types='',...$params) : array
{
  $stmt = new MySQLPreparedSelect($query,$types,wrapped:true);
  return $stmt->fetchOneAssoc(...$params);
}

/**
 * Executes a SELECT query and returns the first value in each row
 * @param string $query Prepared statement query string (with ? pararameter placeholders)
 * @param string $types Prepared statement parameter types (default='')
 * @param array $params Prepared statement parameter values
 * @return array Column value from all matched rows (or [])
   *
   * @note This function only returns the first value from each row, even if the query
   *       selects more than a single column
 */
function MySQLFetchColumn(string $query,string $types='',...$params) : array
{
  $stmt = new MySQLPreparedSelect($query,$types,wrapped:true);
  return $stmt->fetchColumn(...$params);
}

/**
 * Executes a SELECT query and returns first value from first row 
 * @param string $query Prepared statement query string (with ? pararameter placeholders)
 * @param string $types Prepared statement parameter types (default='')
 * @param array $params Prepared statement parameter values
 * @return null|int|float|string Value from query
 * 
 * @note this function only returns the first value from the row, even if the query
 *   selects more than a single column
 */
function MySQLFetchValue(string $query,string $types='',...$params) : null|int|float|string
{
  $stmt = new MySQLPreparedSelect($query,$types,wrapped:true);
  return $stmt->fetchValue(...$params);
}

/**
 * Verifies that the min requred tlc_tt versioning has been implemented.
 *   If not, invoke internal_error to make it immediately obvious that 
 *   something went wrong with the upgrade.
 * @param string $required 
 * @return void 
 */
function verify_required_db_version(string $required) : void
{
  $cur_version = MySQLFetchValue( <<<SQL
    SELECT version from tlc_srv_version_history
     WHERE added in (
       SELECT max(added) from tlc_srv_version_history
     )
    SQL 
  );
  
  if(version_compare($cur_version,$required,'!=')) 
  {
    $config = parse_ini_file(APP_DIR.'/'.PKG_NAME.'.ini',true);
    $schema   = $config['mysql_schema'];
    internal_error("Need to upgrade $schema database version to $required");
  }
}