<?php
namespace tlc\tts;

use mysqli;
use mysqli_stmt;

if(!defined('APP_DIR')) { http_response_code(405); error_log("Invalid entry attempt: ".__FILE__); die(); }

require_once app_file('include/logger.php');

////////////////////////////////////////////////////////////////////////////////
// The MySQLConnnection function creates a single connetion the mysql server.
//   The authentication uses the following parameters initialized from the
//   package config (.ini) file
//
//   tlc-ttsurvey.ini file:
//      HOST     - mysql_host
//      USERNAME - mysql_username
//      PASSWORD - mysql_password
//      SCHEMA   - mysql_host
//
//   Additionally, t sets the charset based on mysql.charset if specified
//   or 'utf8' if not specified.
//
// Note that as logger requires settings from the database to function, 
//   we cannot use any of its logging functions from with MySQLConnection,
//   we must used the native error_log function instead (which will write
//   to the generic PHP error log and not the app specific log).
//   Similarly, we cannot use internal_error as that uses log_error.
//
////////////////////////////////////////////////////////////////////////////////

/**
 * Returns a singleton mysqli connection (constructing it if necessary) based 
 *   on the connection credentials in the config .ini file.
 * 
 * On failure, kills the script with die().
 * 
 * @return mysqli 
 */
function MySQLConnection() 
{
  static $conn;
  if(!$conn) {
    try {
      $config = parse_ini_file(APP_DIR.'/'.PKG_NAME.'.ini',true);
      $username = $config['mysql_username'];
      $password = $config['mysql_password'];
      $schema   = $config['mysql_schema'];
      $host     = $config['mysql_host'];
      $charset  = $config['mysql_charset'] ?? 'utf8mb4';

      mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
      $conn = new \mysqli($host, $username, $password, $schema);
    } 
    catch(\mysqli_sql_exception $e) {
      error_log(sprintf("mysqli(%s, %s, %s, %s)",$host,$username,$password,$schema),0);
      die();
    }
    if( ! $conn->set_charset($charset) ) 
    { 
      // internal_error is ok now as we have a database connection
      internal_error('Failed to set charset to '.$charset);
    }
  }
  return $conn;
}

/**
 * Initiates a mysqli transaction
 * @return void 
 */
function MySQLBeginTransaction() { MySQLConnection()->begin_transaction(); }

/**
 * Rolls back a mysqli transaction
 * @return void 
 */
function MySQLRollback()         { MySQLConnection()->rollback();          }

/**
 * Commits a mysqli transaction
 * @return void 
 */
function MySQLCommit()           { MySQLConnection()->commit();            }


/**
 * Execute a non-SELECT mysqli query/command via a prepared statement
 * 
 * @param string $query Prepared statement query string (with ? pararameter placeholders)
 * @param null|string $types Prepared statement parameter types
 * @param mixed ...$params 
 * @return int|false  Returns:
 *    Returns false if the query failed to execute.
 *    Otherwise, returns the number of updated rows.
 * 
 * @note This function is not to be used with SELECT queries, 
 *       Doing so triggers internal error handling
 */
function MySQLExecute(string $query, ?string $types, ...$params) : int|false
{
  if(preg_match("/^\s*select/i",$query)) {
    internal_error("Use MySQLSelect for select queries");
  }

  $conn = MySQLConnection();

  try {
    if($types) {
      $stmt = $conn->prepare($query);
      $stmt->bind_param($types, ...$params);
      if( $stmt->execute() ) {
        return $stmt->affected_rows;
      }
    } else {
      if($conn->query($query)) {
        return $conn->affected_rows;
      }
    }
  }
  catch(\mysqli_sql_exception $e) {
    log_error($e->getMessage());
  }

  log_warning("Failed:: MySQLExecute($query,$types,".count($params)." params)");
  return false;
}

/**
 * Returns the auto-increment value from the last query
 * @return int
 *
 * @note Must be called immediately after the INSERT query to get the 
 *   autogenerated row ID
 */
function MySQLInsertID() : int
{
  $conn = MySQLConnection();
  return (int) $conn->insert_id;
}

/**
 * Executes a SELECT query and returns the result
 * @param bool $all true:returns all rows, false:returns first row only
 * @param int $mode MYSQLI_ASSOC, MYSQLI_NUM, or MYSQLI_BOTH
 * @param string $query Prepared statement query string (with ? pararameter placeholders)
 * @param null|string $types Prepared statement parameter types
 * @param array $params Prepared statement parameter values
 * @return false|array 
 *    false if query failed to execute
 *    If $all = true,  list of rows
 *    If $all = false, single row or empty array
 *
 * @note This function is only to be used with SELECT queries, 
 *       Doing otherwise triggers internal error handling
 */
function MySQLSelect(bool $all,int $mode,string $query, ?string $types=null,...$params) : false|array
{
  if(! preg_match("/^\s*select/i",$query)) {
    internal_error("Use MySQLSelect for non-select queries");
  }

  $conn = MySQLConnection();

  if($types) {
    $stmt = $conn->prepare($query);
    $stmt->bind_param($types, ...$params);
    if( $stmt->execute() ) {
      $result = $stmt->get_result();
    }
  } else {
    $result = $conn->query($query);
  }

  if($result) {
    if($all) {
      return $result->fetch_all($mode);
    } else {
      return $result->fetch_array($mode);
    }
  }
  log_dev("Failed MySQLSelect($all,$mode,$query,$types,".count($params)." params)");
  return false;
}

/**
 * Executes a SELECT query and returns all results as an array of associative arrays
 * @param string $query Prepared statement query string (with ? pararameter placeholders)
 * @param null|string $types Prepared statement parameter types
 * @param array $params Prepared statement parameter values
 * @return false|array 
 *    false if query failed to execute
 *    [] if no matching rows were found by the query
 *    array of row data as associative arrays
 *
 * @note This function is only to be used with SELECT queries, 
 *       Doing otherwise triggers internal error handling
 */
function MySQLSelectRows(string $query,?string $types=null,...$params) : false|array
{
  return MySQLSelect(true,MYSQLI_ASSOC,$query,$types,...$params);
}

/**
 * Executes a SELECT query and returns the first result as an associative array
 * @param string $query Prepared statement query string (with ? pararameter placeholders)
 * @param null|string $types Prepared statement parameter types
 * @param array $params Prepared statement parameter values
 * @return false|array 
 *    false if query failed to execute
 *    [] if no matching rows were found by the query
 *    associative array corresponding to the first matched row
 *
 * @note This function is only to be used with SELECT queries, 
 *       Doing otherwise triggers internal error handling
 */
function MySQLSelectRow(string $query,?string $types=null,...$params) : false|array
{
  return MySQLSelect(false,MYSQLI_ASSOC,$query,$types,$params);
}

/**
 * Executes a SELECT query and returns all results as an array of indexed arrays
 * @param string $query Prepared statement query string (with ? pararameter placeholders)
 * @param null|string $types Prepared statement parameter types
 * @param array $params Prepared statement parameter values
 * @return false|array 
 *    false if query failed to execute
 *    [] if no matching rows were found by the query
 *    array of row data as indexed arrays
 *
 * @note This function is only to be used with SELECT queries, 
 *       Doing otherwise triggers internal error handling
 */
function MySQLSelectArrays(string $query,?string $types=null,...$params) : false|array
{
  return MySQLSelect(true,MYSQLI_NUM,$query,$types,$params);
}

/**
 * Executes a SELECT query and returns the first result as an indexed array
 * @param string $query Prepared statement query string (with ? pararameter placeholders)
 * @param null|string $types Prepared statement parameter types
 * @param array $params Prepared statement parameter values
 * @return false|array 
 *    false if query failed to execute
 *    [] if no matching rows were found by the query
 *    indexed array corresponding to the first matched row
 *
 * @note This function is only to be used with SELECT queries, 
 *       Doing otherwise triggers internal error handling
 */
function MySQLSelectArray(string $query,?string $types=null,...$params) : false|array
{
  return MySQLSelect(false,MYSQLI_NUM,$query,$types,$params);
}

/**
 * Executes a SELECT query and returns first value in each row
 * @param string $query Prepared statement query string (with ? pararameter placeholders)
 * @param null|string $types Prepared statement parameter types
 * @param array $params Prepared statement parameter values
 * @return false|array 
 *    false if query failed to execute
 *    [] if no matching rows were found by the query
 *    array of row data as strings
 *
 * @note This function is only to be used with SELECT queries, 
 *       Doing otherwise triggers internal error handling
 */
function MySQLSelectValues(string $query,?string $types=null,...$params) : false|array
{
  $rows = MySQLSelectArrays($query,$types,...$params);
  $values = array();
  foreach($rows as $row) { $values[] = $row[0]; }
  return $values;
}

/**
 * Executes a SELECT query and returns first value from first row 
 * @param string $query Prepared statement query string (with ? pararameter placeholders)
 * @param null|string $types Prepared statement parameter types
 * @param array $params Prepared statement parameter values
 * @return null|string Value from query
 *
 * @note This function is only to be used with SELECT queries, 
 *       Doing otherwise triggers internal error handling
 */
function MySQLSelectValue(string $query,?string $types=null,...$params) : ?string
{
  $row = MySQLSelectArray($query,$types,...$params);
  return $row[0] ?? null;
}

class MySQLPreparedSelect
{
  private string $query;
  private string $types;
  private int    $n_params;

  private mysqli      $conn;
  private mysqli_stmt $stmt;

  /**
   * MySQLPreparedSelect constructor
   * @param string $query Prepared statement query string (with ? pararameter placeholders)
   * @param string $types Prepared statement parameter types
   * @return void 
   * 
   * @note This class is only to be used with SELECT queries.  Any other type
   *       of query triggers internal error handling
   */
  public function __construct(string $query, string $types='')
  {
    if (! preg_match("/^\s*select/i", $query)) {
      internal_error(
        "MySQLPreparedSelect only works with SELECT queries:\n" .
        "query: $query"
      );
    }

    $this->n_params = substr_count($query,"?");
    if( strlen($types) !== $this->n_params) {
      internal_error(
        "MySQLPrpeparedSelect mismatch between placeholders and type:\n" .
        "query: $query\ntypes: $types"
      );
    }

    $this->query = $query;
    $this->types = $types;
    $this->conn  = MySQLConnection();
    $this->stmt = $this->conn->prepare($query);
  }

  /**
   * Executes the prepared statement and returns the result
   * @param bool $all true:returns all rows, false:returns first row only
   * @param int $mode MYSQLI_ASSOC, MYSQLI_NUM, or MYSQLI_BOTH
   * @param array $params Prepared statement parameter values
   * @return false|array 
   *    false if query failed to execute
   *    If $all = true,  list of rows
   *    If $all = false, single row or empty array
   */
  private function _exec(bool $all, int $mode, ...$params) : false|array
  {
    $n_input_params = count($params);
    if($n_input_params !== $this->n_params) {
      internal_error(
        "Prepared statement called with wrong number of arguments:\n" .
        "query: ".$this->query."\nexpected ".$this->n_params." params, received $n_input_params"
      );
    }

    if($this->n_params) {
      $this->stmt->bind_param($this->types, ...$params);
    }

    $result = null;
    if($this->stmt->execute()) {
      $result = $this->stmt->get_result();
    }

    if($result) {
      if($all) { return $result->fetch_all($mode);   }
      else     { return $result->fetch_array($mode); }
    }

    log_dev(
      "Failed MySQLPreparedSelect::_exec($all,$mode,$this->query,$this->types,".count($params)." params)\n" .
      "stmt error: $this->stmt->error\n".
      "conn error: $this->conn->error"
    );
    return false;
  }

  /**
   * Executes the prepared statement and returns all results as an array of associative arrays
   * @param array $params Prepared statement parameter values
   * @return false|array 
   *    false if query failed to execute
   *    [] if no matching rows were found by the query
   *    array of row data as associative arrays
   */
  public function fetchAllAssoc(...$params) : false|array 
  {
    return $this->_exec(true, MYSQLI_ASSOC, ...$params);
  }

  /**
   * Executes the prepared statement and returns the first result as an associateive array
   * @param array $params Prepared statement parameter values
   * @return false|array 
   *    false if query failed to execute
   *    [] if no matching rows were found by the query
   *    associative array corresponding to the first matched row
   */
  public function fetchOneAssoc(...$params) : false|array 
  {
    return $this->_exec(false, MYSQLI_ASSOC, ...$params);
  }

  /**
   * Executes the prepared statement and returns all results as an array of indexed arrays
   * @param array $params Prepared statement parameter values
   * @return false|array 
   *    false if query failed to execute
   *    [] if no matching rows were found by the query
   *    array of row data as indexed arrays
   */
  public function fetchAllIndexed(...$params) : false|array 
  {
    return $this->_exec(true, MYSQLI_NUM, ...$params);
  }

  /**
   * Executes the prepared statement and returns the first result as an indexed array
   * @param array $params Prepared statement parameter values
   * @return false|array 
   *    false if query failed to execute
   *    [] if no matching rows were found by the query
   *    associative array corresponding to the first matched row
   */
  public function fetchOneIndexed(...$params) : false|array 
  {
    return $this->_exec(false, MYSQLI_NUM, ...$params);
  }

  /**
   * Executes the prepared statement and returns the first value from each row
   * @param array $params Prepared statement parameter values
   * @return false|array 
   *    false if query failed to execute
   *    [] if no matching rows were found by the query
   *    array of values as strings
   * 
   * @note this function only returns the first value from each row, even if the query
   *   selects more than a single column
   */
  public function fetchColumn(...$params) : false|array
  {
    $rows = $this->fetchAllIndexed(...$params);
    
    if($rows === false) { return false; }
    if(!$rows) { return []; }

    $values = array();
    foreach($rows as $row) { $values[] = $row[0] ?? null; }
    return $values;
  }

  /**
   * Executes the prepared statement and returns the first value from the first row
   * @param array $params Prepared statement parameter values
   * @return null|string Value from query
   * 
   * @note this function only returns the first value from the row, even if the query
   *   selects more than a single column
   */
  public function fetchValue(...$params) : ?string
  {
    $row = $this->fetchOneIndexed(...$params);
    return $row[0] ?? null;
  }
}



/**
 * Verifies that the min requred tlc_tt versioning has been implemented.
 *   If not, invoke internal_error to make it immediately obvious that 
 *   something went wrong with the upgrade.
 * @param string $required 
 * @return void 
 */
function verify_required_db_version(string $required) : void
{
  $query = <<<SQL
    SELECT version from tlc_srv_version_history
     WHERE added in (
       SELECT max(added) from tlc_srv_version_history
     )
  SQL;
  $cur_version = MySQLSelectValue($query);
  
  if(version_compare($cur_version,$required,'!=')) 
  {
    $config = parse_ini_file(APP_DIR.'/'.PKG_NAME.'.ini',true);
    $schema   = $config['mysql_schema'];
    internal_error("Need to upgrade $schema database version to $required");
  }
}