<?php
namespace tlc\tts;

use Exception;
use InvalidArgumentException;
use mysqli_sql_exception;

if(!defined('APP_DIR')) { http_response_code(405); error_log("Invalid entry attempt: ".__FILE__); die(); }

require_once(app_file("include/db.php"));
require_once(app_file("include/settings.php"));
require_once(app_file("include/validation.php"));
require_once(app_file("include/sort_keys.php"));
/**
 * The survey participant information is stored in the tlc_srv_userids table
 * which contains the followinh columns:
 *   id:
 *     - primary key generated by mysql 
 *     - not explicitly used with in the survey app
 *   userid:
 *     - unique ID associated with each survey participant
 *     - selected by the participant when they registered for the survey
 *     - used by the survey app to map participants to their responses
 *   fullname:
 *     - the participant's full name as it will appear on the survey
 *       summary report.
 *     - provided by the participant when they register for the survey
 *     - may be modified by the participant once they have logged in
 *   email:
 *     - the participant's email address (optional)
 *     - provided by the participant when they register for the survey
 *     - may be added/modified by the participant once they have logged in
 *     - may be removed by the participant once they have logged in
 *   password:
 *     - the participant's password for logging into the survey
 *     - provided by the participant when they register for the survey
 *     - may be modified by the participant once they have logged in
 *     - stored internally as a one-way hash of the password
 *
 * The notion of a single access token has been replaced with browser
 *   session access tokens.  These are now handled via access token functions
 *   rather than User.
 **/

class User {
  private ?string $_userid   = null;
  private ?string $_fullname = null;
  private ?string $_email    = null;
  private ?string $_password = null;

  private static $_users = array();

  /**
   * User constructor
   * @param array $user_data 
   * @return void 
   */
  private function __construct(array $user_data)
  {
    // user_data input is expected to be an associative array
    //
    // The data in this array must have been validated/sanitized
    //   BEFORE calling this constructor.  The constructor assumes
    //   it to be valid and complete.

    $this->_userid   = strtolower($user_data['userid']);

    $this->_fullname = $user_data['fullname'];
    $this->_email    = $user_data['email'] ?? null;
    $this->_password = $user_data['password'];
  }

  public function userid()       { return $this->_userid; }
  public function fullname()     { return $this->_fullname; }
  public function email()        { return $this->_email ?? null; }

  /**
   * Looks up a user by either email address or userid
   *   by email if the $needle contains the '@' character
   *   by userid otherwise
   * @param string $needle (userid or email address) 
   * @return null|User|array<User>
   */
  public static function lookup(string $needle) : null|array|User
  {
    if(strstr($needle,"@")) { return self::from_email($needle); }
    else                    { return self::from_userid($needle); }
  }

  /**
   * Looks up a user by userid
   * @param string $userid 
   * @return null|User 
   */
  public static function from_userid(string $userid) : ?User
  {
    $user = self::$_users[$userid] ?? null;
    if(!$user) {
      $r = MySQLFetchOneAssoc('select * from tlc_srv_userids where userid=?','s',$userid);

      if($r) { 
        $user = new User($r); 
        self::$_users[$userid] = $user;
      }
    }
    return $user;
  }

  /**
   * Looks up all users with the specified email address
   *   this allows for multiple logins with the same email 
   * @param string $email 
   * @return array 
   */
  public static function from_email(string $email) : array
  {
    $result = MySQLFetchAllAssoc('select * from tlc_srv_userids where email=?','s',$email);

    $users = [];
    foreach($result as $user_data) {
      $userid = strtolower($user_data['userid']);

      $cur_user = self::$_users[$userid] ?? null;
      if($cur_user) {
        $users[] = $cur_user;
      } else {
        $user = new User($user_data);
        $users[] = $user;
        self::$_users[$userid] = $user;
      }
    }
    return $users;
  }

  /**
   * Returns all registered users
   * @return array<User> 
   */
  public static function all_users() : array
  {
    // note this function bypasses the user cache.  It is 
    //   meant to only be used in admin capabilities
    $result = MySQLFetchAllAssoc('select * from tlc_srv_userids');
    $users = [];
    foreach($result as $user_data) {
      $users[] = new User($user_data);
    }
    return $users;
  }

  // Full Name

  /**
   * Sets the user's fullname in the database 
   * @param string $fullname 
   * @return bool true=name updated, false=no change necessary
   * @throws InvalidArgumentException on invalid fullname argument
   * @throws mysqli_sql_exception on MySQL error
   */
  public function set_fullname(string $fullname) : bool
  {
    $error = null;
    if(!adjust_and_validate_user_input('fullname',$fullname,$error)) {
      throw new InvalidArgumentException("Invalid fullname ($fullname): $error");
    }
    $changed = MySQLExecute('update tlc_srv_userids set fullname=? where userid=?','ss',$fullname,$this->_userid);
    if($changed) { $this->_fullname = $fullname; }
    return $changed > 0;
  }

  // Email

  /**
   * Sets or clears the user's email address in the database
   * @param null|string $email (will clear email on falsey value)
   * @return bool true=email updated (or cleared), false = no change necessary
   * @throws InvalidArgumentException on invalid email argument
   * @throws mysqli_sql_exception on MySQL error
   */
  public function set_email(?string $email) : bool
  {
    $error = null;
    if(!adjust_and_validate_user_input('email',$email,$error)) {
      throw new InvalidArgumentException("Invalid email: $error");
    }
    if($email) {
      $changed = MySQLExecute('update tlc_srv_userids set email=? where userid=?','ss',$email,$this->_userid);
    } else {
      $changed = MySQLExecute('update tlc_srv_userids set email=NULL where userid=?','s',$this->_userid);
    }

    if($changed) { $this->_email = $email; }
    return $changed > 0;
  }

  /**
   * Clears the user's email in the database
   * @return bool true=email cleared), false = no change necessary
   * @throws mysqli_sql_exception on MySQL error
   * @return bool 
   */
  public function clear_email() : bool { return $this->set_email(null);            }

  // Profile (fullname + email)

  /**
   * Sets updates the user fullname and email address as needed
   * @param string $fullname 
   * @param null|string $email (will clear email on falsey value)
   * @return bool true=name or email updated, false=no change necessary
   * @throws InvalidArgumentException on invalid fullname or email argument
   * @throws mysqli_sql_exception on MySQL error
   */
  public function update_profile(string $fullname,?string $email=null) : bool
  {
    // Grab the current values for fullname and email in case we need to reset them
    $old_fullname = $this->_fullname;
    $old_email    = $this->_email;
    
    $rval = false;
    try {
      MySQLBeginTransaction();
      $rval = $rval || $this->set_fullname($fullname); 
      $rval = $rval || $this->set_email($email); 
      MySQLCommit();
    }
    catch(Exception $e) {
      MySQLRollback();
      $this->_fullname = $old_fullname;
      $this->_email    = $old_email;
      $rval = false;
    }
    return $rval;
  }

  /**
   * Sets updates the user fullname and email address as needed and sends an
   *   email notification (if address is known) to both the new and old (if 
   *   changed) email addresses
   * 
   * @param string $fullname 
   * @param null|string $email (will clear email on falsey value)
   * @return bool true=name or email updated, false=no change necessary
   * @throws InvalidArgumentException on invalid fullname or email argument
   * @throws mysqli_sql_exception on MySQL error
   * 
   * @note return value only pertains to whether or not profile data changed in
   *       the database.  As the sendmail functions are asynchronous and as the 
   *       intent is to indicate changes in the database, the result of the sendmail
   *       function calls is NOT included in the return value.
   */
  public function update_profile_and_notify(string $fullname,?string $email=null) : bool
  {
    $old_fullname = $this->_fullname;
    $old_email    = $this->_email;

    $changed = $this->update_profile($fullname,$email);
    if(!$changed) { return false; }

    require_once app_file('include/sendmail.php');

    // determine if this is a change to the user's email address
    $is_new_email = ($email !== $old_email);

    // Send profile update notification to new (possibly existing) email address
    if($email) {
      $to = $is_new_email ? 'to new address' : 'to';
      log_info("Sending updated profile $to: $email");
      sendmail_profile($email, $this->userid(), [
        'name' =>[$old_fullname, $fullname],
        'email'=>[$old_email,$email]
      ]);
    }
    // If this is a new email address, send update notification to old address 
    //   (if known) as well (just in case this change wasn't authorized)
    if($is_new_email && $old_email) {
      log_info("Sending updated profile to old address: $old_email");
      require_once app_file('include/sendmail.php');
      sendmail_profile($old_email, $this->userid(), [
        'name' =>[$old_fullname, $fullname],
        'email'=>[$old_email,$email]
      ]);
    }

    return true;
  }


  // Password

  /**
   * Verifies that the specified passsword matches the hashed password
   *   in the database. (see php's validate_password)
   * @param string $password 
   * @return bool 
   */
  public function validate_password(string $password) : bool
  {
    return password_verify($password,$this->_password);
  }

  /**
   * Generates a random token to be used for a password reset request.
   *   The caller may request that the token be somewhat memorable
   *   (a 4 character adjective followed by a 6 character noun) or
   *   fully random.
   * @param bool $from_wordlist true=adj+noun, false=fully random
   * @return string 
   */
  public function get_password_reset_token(bool $from_wordlist=false) : string
  {
    // Only one active reset request at a time
    MySQLExecute("delete from tlc_srv_reset_tokens where userid=?",'s',$this->_userid);
    if($from_wordlist) {
      require_once(app_file('include/token_words.php'));
      $adj  = $adj4_txt[array_rand($adj4_txt)];
      $noun = $noun6_txt[array_rand($noun6_txt)];
      $token = strtoupper($adj . $noun);
    } else {
      $token = gen_token(pwreset_length());
    } 
    $expires = time() + 60*pwreset_timeout();
    $expires = gmdate('Y-m-d H:i:s', $expires);
    $r = MySQLExecute("insert into tlc_srv_reset_tokens values (?,'$token','$expires')",'s',$this->_userid);

    return $r ? $token : null;
  }

  /**
   * Attempts to perfom a password reset given a reset token and a new password
   * @param string $token 
   * @param string $password 
   * @param null|string &$error On failure, indicates the reason for failure
   * @return bool true=password updated and notification sent, false=failed to update password
   * @note success does not necessarily mean a notification was sent, only that an attempt
   *       was made to send it.  If the email address is incorrect or there is an issue with
   *       the SMTP server, this method will still return true.
   */
  public function update_password(string $token,string $password,?string &$error=null) : bool
  {
    $error = null;
    $result = MySQLFetchOneAssoc('select token,expires from tlc_srv_reset_tokens where userid=?','s', $this->_userid);
    if(!$result) {
      $error = "No current password reset request";
      return false;
    }
    // You only get one chance per reset request
    MySQLExecute('delete from tlc_srv_reset_tokens where userid=?','s',$this->_userid);
    if( $token !== $result['token'] ) {
      $error = "Invalid reset request";
      return false;
    }
    $expires = strtotime($result['expires'].' UTC');
    $now = time();
    if($now > $expires) {
      $error = "Password reset request has expired";
      return false;
    }

    $rval = $this->set_password_and_notify($password);
    if(!$rval) { $error = 'Invalid password'; }

    return $rval;
  }

  /**
   * Sets the user's password to the specified value
   * @param string $password 
   * @return bool true=success, false=invalid password
   */
  public function set_password(string $password) : bool
  {
    // Note this function will return: 
    //   false if there was an issue with the update command
    //   0     if the command was ok, but no database update was needed
    //   1     if the command was ok and the password was updated

    if(!adjust_and_validate_user_input('password',$password) ) {
      log_info("Cannot update password for $this->_userid: invalid password");
      return false;
    }
    $password = password_hash($password,PASSWORD_DEFAULT);

    try {
      MySQLExecute('update tlc_srv_userids set password=? where userid=?', 'ss', $password, $this->_userid);
      $this->_password = $password;
      return true;
    } catch(mysqli_sql_exception $e) {
      internal_error("Mysterious failure to update password in database: ".$e->getMessage());
      // won't actually return, but to keep the linter happy...
      return false;
    }
  }

  /**
   * Sets the user's password and notifies them of the change 
   *   (if they provided an email address)
   * @param string $password 
   * @return bool 
   */
  public function set_password_and_notify(string $password) : bool
  {
    $rval = $this->set_password($password);

    if($rval) { 
      $email = $this->email();
      if($email) {
        require_once app_file('include/sendmail.php');
        sendmail_profile($email, $this->userid(), ['password']);
      }
    }
    return $rval;
  }
}


/**
 * Creates a new userid and associated access token
 * @param string $userid 
 * @param string $fullname 
 * @param string $password 
 * @param null|string $email 
 * @return null|User 
 */
function create_new_user(string $userid,string $fullname,string $password,?string $email=null) : ?User
{
  $userid = strtolower($userid);

  // inputs should be validated before calling this function... but as
  //   we're about to add this to the database, we'll validate them
  //   one last time.  If there is an issue, then there is an internal
  //   error in the app... so die

  $error = '';
  if(!adjust_and_validate_user_input('userid',$userid,$error)) {
    internal_error("Error while creating new user: userid $error");
  }
  if(!adjust_and_validate_user_input('fullname',$fullname,$error)) {
    internal_error("Error while creating new user: fullname $error");
  }
  if(!adjust_and_validate_user_input('password',$password,$error)) {
    internal_error("Error while creating new user: password $error");
  }
  if(!adjust_and_validate_user_input('email',$email,$error)) {
    internal_error("Error while creating new user: email $error");
  }

  try {
    MySQLBeginTransaction();

    $token    = gen_token();
    $password = password_hash($password, PASSWORD_DEFAULT);

    if ($email) {
      MySQLExecute(
        "insert into tlc_srv_userids (userid,fullname,email,password) values (?,?,?,?)",
        "ssss", $userid, $fullname, $email, $password
      );
    } else {
      MySQLExecute(
        "insert into tlc_srv_userids (userid,fullname,password) values (?,?,?)",
        "sss", $userid, $fullname, $password
      );
    }

    $token = generate_access_token($userid);
    if (!$token) {
      internal_error("Error while creating new user: could not create access token for $userid");
    }

    MySQLCommit();

    $new_user = User::from_userid($userid);
  }
  catch(\Exception $e) {
    MySQLRollback();
    log_warning("Failed to create new user: $e->");
    $new_user = null;
  }
  return $new_user;
}

/**
 * Verifies that the specified password for the spececified user matches
 *   the hashed password in the database.
 * @param string $userid 
 * @param string $password 
 * @return bool 
 */
function validate_user_password(string $userid,string $password) : bool
{
  $userid = strtolower($userid);

  $user = User::from_userid($userid);
  if(!$user) {
    log_info("Failed to validate password for $userid (invalid userid)");
    return false;
  }
  if(!$user->validate_password($password)) {
    log_info("Failed to validate password for $userid (invalid password)");
    return false;
  }
  return true;
}

/**
 * Sorts a list of userid based on the associated fullname 
 * @param string[] &$userids 
 * @return void 
 */
function sort_userids_by_fullname(array &$userids)
{
  $fullname_keys = [];
  foreach($userids as $userid) {
    $fullname_keys[$userid] = surname_sort_key(User::from_userid($userid)->fullname());
  }
  asort($fullname_keys);
  $userids = array_keys($fullname_keys);
}