drop table if exists bkp_anonids;
drop table if exists bkp_question_map;
drop table if exists bkp_question_options;
drop table if exists bkp_response_options;
drop table if exists bkp_responses;
drop table if exists bkp_roles;
drop table if exists bkp_section_feedback;
drop table if exists bkp_settings;
drop table if exists bkp_strings;
drop table if exists bkp_survey_options;
drop table if exists bkp_survey_questions;
drop table if exists bkp_surveys;
drop table if exists bkp_survey_sections;
drop table if exists bkp_userids;
drop table if exists bkp_user_status;
drop table if exists bkp_version_history;

create table bkp_anonids          as select * from tlc_tt_anonids;
create table bkp_question_map     as select * from tlc_tt_question_map;
create table bkp_question_options as select * from tlc_tt_question_options;
create table bkp_response_options as select * from tlc_tt_response_options;
create table bkp_responses        as select * from tlc_tt_responses;
create table bkp_roles            as select * from tlc_tt_roles;
create table bkp_section_feedback as select * from tlc_tt_section_feedback;
create table bkp_settings         as select * from tlc_tt_settings;
create table bkp_strings          as select * from tlc_tt_strings;
create table bkp_survey_options   as select * from tlc_tt_survey_options;
create table bkp_survey_questions as select * from tlc_tt_survey_questions;
create table bkp_surveys          as select * from tlc_tt_surveys;
create table bkp_survey_sections  as select * from tlc_tt_survey_sections;
create table bkp_userids          as select * from tlc_tt_userids;
create table bkp_user_status      as select * from tlc_tt_user_status;
create table bkp_version_history  as select * from tlc_tt_version_history;
