drop table if exists tlc_bkp_response_options;
drop table if exists tlc_bkp_responses;
drop table if exists tlc_bkp_reminder_emails;
drop table if exists tlc_bkp_user_status;
drop table if exists tlc_bkp_roles;
drop table if exists tlc_bkp_reset_tokens;
drop table if exists tlc_bkp_access_tokens;
drop table if exists tlc_bkp_userids;
drop table if exists tlc_bkp_question_options;
drop table if exists tlc_bkp_survey_options;
drop table if exists tlc_bkp_group_content;
drop table if exists tlc_bkp_section_content;
drop table if exists tlc_bkp_sections;
drop table if exists tlc_bkp_groups;
drop table if exists tlc_bkp_questions;
drop table if exists tlc_bkp_surveys;
drop table if exists tlc_bkp_settings;
drop table if exists tlc_bkp_version_history;

create table tlc_bkp_version_history  as select * from tlc_srv_version_history;
create table tlc_bkp_settings         as select * from tlc_srv_settings;
create table tlc_bkp_surveys          as select * from tlc_srv_surveys;
create table tlc_bkp_questions        as select * from tlc_srv_questions;
create table tlc_bkp_groups           as select * from tlc_srv_groups;
create table tlc_bkp_sections         as select * from tlc_srv_sections;
create table tlc_bkp_section_content  as select * from tlc_srv_section_content;
create table tlc_bkp_group_content    as select * from tlc_srv_group_content;
create table tlc_bkp_survey_options   as select * from tlc_srv_survey_options;
create table tlc_bkp_question_options as select * from tlc_srv_question_options;
create table tlc_bkp_userids          as select * from tlc_srv_userids;
create table tlc_bkp_access_tokens    as select * from tlc_srv_access_tokens;
create table tlc_bkp_reset_tokens     as select * from tlc_srv_reset_tokens;
create table tlc_bkp_roles            as select * from tlc_srv_roles;
create table tlc_bkp_user_status      as select * from tlc_srv_user_status;
create table tlc_bkp_reminder_emails  as select * from tlc_srv_reminder_emails;
create table tlc_bkp_responses        as select * from tlc_srv_responses;
create table tlc_bkp_response_options as select * from tlc_srv_response_options;
