drop table if exists tlc_bkp_anonids;
drop table if exists tlc_bkp_question_map;
drop table if exists tlc_bkp_question_options;
drop table if exists tlc_bkp_response_options;
drop table if exists tlc_bkp_responses;
drop table if exists tlc_bkp_roles;
drop table if exists tlc_bkp_section_feedback;
drop table if exists tlc_bkp_settings;
drop table if exists tlc_bkp_strings;
drop table if exists tlc_bkp_survey_options;
drop table if exists tlc_bkp_survey_questions;
drop table if exists tlc_bkp_surveys;
drop table if exists tlc_bkp_survey_sections;
drop table if exists tlc_bkp_userids;
drop table if exists tlc_bkp_access_tokens;
drop table if exists tlc_bkp_user_status;
drop table if exists tlc_bkp_version_history;

create table tlc_bkp_version_history  as select * from tlc_tt_version_history;
create table tlc_bkp_anonids          as select * from tlc_tt_anonids;
create table tlc_bkp_question_map     as select * from tlc_tt_question_map;
create table tlc_bkp_question_options as select * from tlc_tt_question_options;
create table tlc_bkp_response_options as select * from tlc_tt_response_options;
create table tlc_bkp_responses        as select * from tlc_tt_responses;
create table tlc_bkp_roles            as select * from tlc_tt_roles;
create table tlc_bkp_section_feedback as select * from tlc_tt_section_feedback;
create table tlc_bkp_settings         as select * from tlc_tt_settings;
create table tlc_bkp_strings          as select * from tlc_tt_strings;
create table tlc_bkp_survey_options   as select * from tlc_tt_survey_options;
create table tlc_bkp_survey_questions as select * from tlc_tt_survey_questions;
create table tlc_bkp_surveys          as select * from tlc_tt_surveys;
create table tlc_bkp_survey_sections  as select * from tlc_tt_survey_sections;
create table tlc_bkp_userids          as select * from tlc_tt_userids;
create table tlc_bkp_access_tokens    as select * from tlc_tt_access_tokens;
create table tlc_bkp_user_status      as select * from tlc_tt_user_status;
