delete from tlc_srv_response_options;
delete from tlc_srv_responses;
delete from tlc_srv_reminder_emails;
delete from tlc_srv_user_status;
delete from tlc_srv_roles;
delete from tlc_srv_reset_tokens;
delete from tlc_srv_access_tokens;
delete from tlc_srv_userids;
delete from tlc_srv_question_options;
delete from tlc_srv_survey_options;
delete from tlc_srv_group_content;
delete from tlc_srv_section_content;
delete from tlc_srv_sections;
delete from tlc_srv_groups;
delete from tlc_srv_questions;
delete from tlc_srv_surveys;
delete from tlc_srv_settings;
delete from tlc_srv_version_history;

insert into tlc_srv_version_history  select * from tlc_bkp_version_history;
insert into tlc_srv_settings         select * from tlc_bkp_settings;
insert into tlc_srv_surveys          select * from tlc_bkp_surveys;
insert into tlc_srv_questions        select * from tlc_bkp_questions;
insert into tlc_srv_groups           select * from tlc_bkp_groups;
insert into tlc_srv_sections         select * from tlc_bkp_sections;
insert into tlc_srv_section_content  select * from tlc_bkp_section_content;
insert into tlc_srv_group_content    select * from tlc_bkp_group_content;
insert into tlc_srv_survey_options   select * from tlc_bkp_survey_options;
insert into tlc_srv_question_options select * from tlc_bkp_question_options;
insert into tlc_srv_userids          select * from tlc_bkp_userids;
insert into tlc_srv_access_tokens    select * from tlc_bkp_access_tokens;
insert into tlc_srv_reset_tokens     select * from tlc_bkp_reset_tokens;
insert into tlc_srv_roles            select * from tlc_bkp_roles;
insert into tlc_srv_user_status      select * from tlc_bkp_user_status;
insert into tlc_srv_reminder_emails  select * from tlc_bkp_reminder_emails;
insert into tlc_srv_responses        select * from tlc_bkp_responses;
insert into tlc_srv_response_options select * from tlc_bkp_response_options;
