delete from tlc_tt_access_tokens;
delete from tlc_tt_reminder_emails;
delete from tlc_tt_response_options;
delete from tlc_tt_section_feedback;
delete from tlc_tt_responses;
delete from tlc_tt_user_status;
delete from tlc_tt_settings;
delete from tlc_tt_roles;
delete from tlc_tt_reset_tokens;
delete from tlc_tt_anonids;
delete from tlc_tt_userids;
delete from tlc_tt_question_options;
delete from tlc_tt_question_map;
delete from tlc_tt_survey_questions;
delete from tlc_tt_survey_sections;
delete from tlc_tt_survey_options;
delete from tlc_tt_surveys;
delete from tlc_tt_strings;
delete from tlc_tt_version_history;

insert into tlc_tt_version_history  select * from tlc_bkp_version_history;
insert into tlc_tt_strings (string_id,str) select string_id,str from tlc_bkp_strings;
insert into tlc_tt_surveys          select * from tlc_bkp_surveys;
insert into tlc_tt_survey_options   select * from tlc_bkp_survey_options;
insert into tlc_tt_survey_sections  select * from tlc_bkp_survey_sections;
insert into tlc_tt_survey_questions select * from tlc_bkp_survey_questions;
insert into tlc_tt_question_map     select * from tlc_bkp_question_map;
insert into tlc_tt_question_options select * from tlc_bkp_question_options;
insert into tlc_tt_userids          select * from tlc_bkp_userids;
insert into tlc_tt_anonids          select * from tlc_bkp_anonids;
insert into tlc_tt_roles            select * from tlc_bkp_roles;
insert into tlc_tt_settings         select * from tlc_bkp_settings;
insert into tlc_tt_user_status      select * from tlc_bkp_user_status;
insert into tlc_tt_responses        select * from tlc_bkp_responses;
insert into tlc_tt_section_feedback select * from tlc_bkp_section_feedback;
insert into tlc_tt_response_options select * from tlc_bkp_response_options;
insert into tlc_tt_reminder_emails  select * from tlc_bkp_reminder_emails;
insert into tlc_tt_access_tokens    select * from tlc_bkp_access_tokens;
